{
 "title": "REG.RU - pagespeed - detail",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "url", "label": "URL", "query": "pagespeed_speedindex" },
   {
    "name": "overall",
    "query": "{url=\"$url\", type=\"overall\"}"
   }
  ]
 },
 "panels": [
  { "title": "Основные метрики страницы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance - score",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_total_performance_score{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_first_contentful_paint{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_speedindex{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Performance - score in time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_total_performance_score{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "First meaningful paint",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_first_meaningful_paint{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Mainthred work breakdown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_mainthread_work_breakdown{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Time to interactive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_timetointeractive{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "First Cpu Idle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_first_cpu_idle_score{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Основные метрики в секундах", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Speed Index - динамика в ms",
   "type": "graph",
   "description": "Speed Index shows how quickly the contents of a page are visibly populated. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/speed-index).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_speedindex_displayvalue{url=\"$url\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "First Contentful Paint - динамика в ms",
   "type": "graph",
   "description": "First Contentful Paint marks the time at which the first text or image is painted. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_first_contentful_paint_displayvalue{url=\"$url\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Time to Interactive - динамика в ms",
   "type": "graph",
   "description": "Time to interactive is the amount of time it takes for the page to become fully interactive. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/consistently-interactive).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_timetointeractive_displayvalue{url=\"$url\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "First meaningful paint - динамика в ms",
   "type": "graph",
   "description": "First Meaningful Paint measures when the primary content of a page is visible. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_first_meaningful_paint_displayvalue{url=\"$url\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Mainthred work breackdown - динамика в ms",
   "type": "graph",
   "description": "Consider reducing the time spent parsing, compiling and executing JS.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_mainthread_work_breakdown_displayvalue{url=\"$url\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "First CPU idle - динамика в ms",
   "type": "graph",
   "description": "First CPU Idle marks the first time at which the page's main thread is quiet enough to handle input. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/first-interactive).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_first_cpu_idle_score_displayvalue{url=\"$url\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Детальные метрики страницы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Timing Total of Page load (sec)",
   "type": "graph",
   "description": "Общая скорость загрузки страницы в сек",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_total_time_page_load{url=\"$url\"} / 10000",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 37 },
   "content": "\n# Total time page load\n\nПоказывает как долго загружалась страница в миллисекундах\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Avoid multiple page redirects - score",
   "type": "graph",
   "description": "Redirects introduce additional delays before the page can be loaded. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/redirects).",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_redirects{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 45 },
   "content": "\n# Redirects\n\nПеренаправления на странице заставляют браузер перезапрашивать заново новое размещение,на что тратиться доп время\n\noverallSavingsMs - на сколько мс можно ускорить страницу\n\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 50 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"redirects\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Minify JavaScript - score",
   "type": "graph",
   "description": "Minifying JavaScript files can reduce payload sizes and script parse time. [Learn more](https://developers.google.com/speed/docs/insights/MinifyResources).",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_unminified_javascript{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 53 },
   "content": "\n# Minify JavaScript\n\nMinifying JavaScript files can reduce payload sizes and script parse time. [Learn more](https://developers.google.com/speed/docs/insights/MinifyResources).\n\noverallSavingsMs - на сколько мс можно ускорить страницу\n\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"unminified_javascript\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Preload key requests - score",
   "type": "graph",
   "description": "Consider using <link rel=preload> to prioritize fetching resources that are currently requested later in page load. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/preload).",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_uses_rel_preconnect{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 61 },
   "content": "\n# Preload key requests\n\nConsider using <link rel=preload> to prioritize fetching resources that are currently requested later in page load. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/preload).\n\noverallSavingsMs - на сколько мс можно ускорить страницу\n\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"uses_rel_preload\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Dom size - score",
   "type": "graph",
   "description": "Browser engineers recommend pages contain fewer than ~1,500 DOM elements. The sweet spot is a tree depth < 32 elements and fewer than 60 children/parent element. A large DOM can increase memory usage, cause longer [style calculations](https://developers.google.com/web/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations), and produce costly [layout reflows](https://developers.google.com/speed/articles/reflow). [Learn more](https://developers.google.com/web/tools/lighthouse/audits/dom-size)",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_dom_size{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 69 },
   "content": "\n# Dom size\nОптимальное количество блоков:\n* Has less than 1500 nodes total.\n* Has a maximum depth of 32 nodes.\n* Has no parent node with more than 60 child nodes.\n\nBrowser engineers recommend pages contain fewer than ~1,500 DOM elements. The sweet spot is a tree depth < 32 elements and fewer than 60 children/parent element. A large DOM can increase memory usage, cause longer [style calculations](https://developers.google.com/web/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations), and produce costly [layout reflows](https://developers.google.com/speed/articles/reflow). [Learn more](https://developers.google.com/web/tools/lighthouse/audits/dom-size).\n\n\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Количество блоков - текущее",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 74 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pagespeed_dom_size_displayvalue{url=\"$url\"} * 1000",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Uses webp images - score",
   "type": "graph",
   "description": "Image formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/webp).",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_uses_webp_images{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 77 },
   "content": "\n# Uses webp images\n\nImage formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/webp).\n\noverallSavingsMs - на сколько мс можно ускорить страницу\n\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 82 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"uses_webp_images\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Total byte weight - score",
   "type": "graph",
   "description": "Large network payloads cost users real money and are highly correlated with long load times. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/network-payloads).",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_total_byte_weight_score{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 85 },
   "content": "\n# Total byte weight\n\n\"Large network payloads cost users real money and are highly correlated with long load times. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/network-payloads).\n\nРекомендовано не более 1600 kb\n\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total size payloads - текущее",
   "type": "singlestat",
   "description": "Большого размера пакеты могут тратить много времени на загрузку по сети",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 90 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_total_byte_weight_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Unused css rules - score",
   "type": "graph",
   "description": "Remove dead rules from stylesheets and defer the loading of CSS not used for above-the-fold content to reduce unnecessary bytes consumed by network activity. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/unused-css).",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_unused_css_rules{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 93 },
   "content": "\n# Unused css rules\n\nRemove dead rules from stylesheets and defer the loading of CSS not used for above-the-fold content to reduce unnecessary bytes consumed by network activity. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/unused-css).\n\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 97 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"unused_css_rules\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Неиспользуемых css правил - текущее",
   "type": "singlestat",
   "description": "Количество не используемых но загружаемых на страницу css  правил",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 99 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_unused_css_rules_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Uses responsive images - score",
   "type": "graph",
   "description": "Serve images that are appropriately-sized to save cellular data and improve load time. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/oversized-images).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_uses_responsive_images{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 101 },
   "content": "\n# Properly size images\n\nServe images that are appropriately-sized to save cellular data and improve load time. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/oversized-images).\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 106 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"uses_responsive_images\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Offscreen images - score",
   "type": "graph",
   "description": "Consider lazy-loading offscreen and hidden images after all critical resources have finished loading to lower time to interactive. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/offscreen-images).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_offscreen_images{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 110 },
   "content": "\n# Defer offscreen images\n\nConsider lazy-loading offscreen and hidden images after all critical resources have finished loading to lower time to interactive. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/offscreen-images).\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 114 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"offscreen_images\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Cохранить кб - текущее",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 117 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_offscreen_images_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Network server latency (ms)",
   "type": "graph",
   "description": "Server latencies can impact web performance. If the server latency of an origin is high, it's an indication the server is overloaded or has poor backend performance. [Learn more](https://hpbn.co/primer-on-web-performance/#analyzing-the-resource-waterfall).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_network_server_latency_displayvalue{url=\"$url\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 119 },
   "content": "\n# Server Backend Latencies\n\nServer latencies can impact web performance. If the server latency of an origin is high, it's an indication the server is overloaded or has poor backend performance. [Learn more](https://hpbn.co/primer-on-web-performance/#analyzing-the-resource-waterfall).\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Display Value",
   "type": "singlestat",
   "description": "Наличие задержки от бэкенда в ms",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 124 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_network_server_latency_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Unminified css - score",
   "type": "graph",
   "description": "Minifying CSS files can reduce network payload sizes. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/minify-css).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_unminified_css{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 128 },
   "content": "\n# Minify CSS\n\nMinifying CSS files can reduce network payload sizes. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/minify-css)",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 134 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"unminified_css\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Bootup time - score",
   "type": "graph",
   "description": "Consider reducing the time spent parsing, compiling, and executing JS. You may find delivering smaller JS payloads helps with this. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/bootup).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_bootup_time{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 137 },
   "content": "\n# Reduce JavaScript execution time\n\nConsider reducing the time spent parsing, compiling, and executing JS. You may find delivering smaller JS payloads helps with this. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/bootup)",
   "targets": [
    {}
   ]
  },
  {
   "title": "Display Value",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 142 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_bootup_time_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Uses rel preconnect - score",
   "type": "graph",
   "description": "Consider adding preconnect or dns-prefetch resource hints to establish early connections to important third-party origins. [Learn more](https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect).",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_uses_rel_preconnect{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 146 },
   "content": "\n# Preconnect to required origins\n\nConsider adding preconnect or dns-prefetch resource hints to establish early connections to important third-party origins. [Learn more](https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect).",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 151 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"uses_rel_preconnect\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Estimated input latency time - score",
   "type": "graph",
   "description": "Estimated Input Latency is an estimate of how long your app takes to respond to user input, in milliseconds, during the busiest 5s window of page load. If your latency is higher than 50 ms, users may perceive your app as laggy. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/estimated-input-latency)",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_estimated_input_latency_time{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 154 },
   "content": "\n# Estimated Input Latency\n\nEstimated Input Latency is an estimate of how long your app takes to respond to user input, in milliseconds, during the busiest 5s window of page load. If your latency is higher than 50 ms, users may perceive your app as laggy. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/estimated-input-latency).",
   "targets": [
    {}
   ]
  },
  {
   "title": "Display Value",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 159 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_estimated_input_latency_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Total blocking time",
   "type": "graph",
   "description": "Sum of all time periods between FCP and Time to Interactive, when task length exceeded 50ms, expressed in milliseconds.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_total_blocking_time{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 163 },
   "content": "\n# Total Blocking Time\n\nSum of all time periods between FCP and Time to Interactive, when task length exceeded 50ms, expressed in milliseconds.",
   "targets": [
    {}
   ]
  },
  {
   "title": "Display Value",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 168 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_total_blocking_time_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Max potential fid - score",
   "type": "graph",
   "description": "The maximum potential First Input Delay that your users could experience is the duration, in milliseconds, of the longest task. [Learn more](https://developers.google.com/web/updates/2018/05/first-input-delay).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_max_potential_fid{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 172 },
   "content": "\n# Max Potential First Input Delay\n\nThe maximum potential First Input Delay that your users could experience is the duration, in milliseconds, of the longest task. [Learn more](https://developers.google.com/web/updates/2018/05/first-input-delay).",
   "targets": [
    {}
   ]
  },
  {
   "title": "Display Value",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 177 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_max_potential_fid_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Uses long cache ttl - score",
   "type": "graph",
   "description": "A long cache lifetime can speed up repeat visits to your page. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/cache-policy).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_uses_long_cache_ttl{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 181 },
   "content": "\n# Serve static assets with an efficient cache policy\n\nA long cache lifetime can speed up repeat visits to your page. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/cache-policy).",
   "targets": [
    {}
   ]
  },
  {
   "title": "Display Value",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 186 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_uses_long_cache_ttl_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Uses optimized images - score",
   "type": "graph",
   "description": "Optimized images load faster and consume less cellular data. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/optimize-images).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_uses_optimized_images{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 190 },
   "content": "\n# Efficiently encode images\n\nOptimized images load faster and consume less cellular data. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/optimize-images)",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 195 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"uses_optimized_images\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Uses text compression - score",
   "type": "graph",
   "description": "Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/text-compression).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_uses_text_compression{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 199 },
   "content": "\n# Enable text compression\n\nText-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/text-compression)",
   "targets": [
    {}
   ]
  },
  {
   "title": "overallSavingsMs - текущее",
   "type": "singlestat",
   "description": "Сколько мс можно выкружить для страницы если все сделать\" правильно\"",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 204 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{url=\"$url\", type=\"overall\", id=\"uses_text_compression\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Render blocking resources - score",
   "type": "graph",
   "description": "Resources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/blocking-resources).",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "pagespeed_render_blocking_resources{url=\"$url\"} * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$url",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Описание",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 208 },
   "content": "\n# Eliminate render-blocking resources\n\nResources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/blocking-resources)",
   "targets": [
    {}
   ]
  },
  {
   "title": "Display Value",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 213 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pagespeed_render_blocking_resources_displayvalue{url=\"$url\"}",
     "legendFormat": "{{display_value}}"
    }
   ]
  },
  {
   "title": "Аналитические метрики",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 217 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 скачков просадки Speed Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "topk(5, pagespeed_speedindex{url=\"$url\"}) * 100",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  }
 ]
}